[project]
name = "smsspamclassifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ajinath idhate", email = "ajinathidhate97@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "streamlit>=1.65.0",
    "wordcloud>=1.9.6",
    "xgboost>=3.4.1",
]

[project.scripts]
smsspamclassifier = "smsspamclassifier:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
